### ISSUE TITLE
[Bug]: OPIK: Failed to process CreateSpansBatchMessage.

### ISSUE THREAD

**Issue by Badrinarayana26** [comet-ml/opik#746]
### What component(s) are affected?

- [ ] Python SDK
- [ ] Opik UI
- [ ] Opik Server
- [ ] Documentation

### Opik version

- Opik version: 1.1.12

### Describe the problem

I have set the OPIK_URL_OVERRIDE and also the project globally using os.environ. I can see that whenever open ai is called the prompt and the tokens are being traced but it is not reflected in the local host. 

It says Failed to process CreateSpansBatchMessage.

**Comment by jverre** [comment]
Hi @Badrinarayana26 
Can you share the error message you are facing and the code you are running ? I haven't seen this error in a while when I use the platform

**Comment by Badrinarayana26** [comment]
Hello @jverre 
Here is the part of the code where I am trying to trace the llm function : 

api_key = os.getenv("OPENAI_API_KEY")

os.environ["OPIK_URL_OVERRIDE"] = "http://localhost:5173/api"
os.environ["OPIK_PROJECT_NAME"] = "Default Project"
openai_client = OpenAI()
openai_client = track_openai(openai_client)

# openai = OpenAI()
model = os.getenv('gpt_model')

async def engine(prompts, temperature):
    """
    Generate a LLM engine response based on input data.

    :param prompts: Input prompts.
    :param temperature: Input temperature.
    :return: Generated content response
    """
    try:
        prompt = prompts
        response = openai_client.chat.completions.create(
            model=model,  # You can update the engine if a newer one is available.
            messages=[
                {"role": "system", "content": prompt},
            ],
            temperature=temperature,
            # Adjust creativity. 0.7 is a good starting point for varied yet coherent questions.
            stop=None,
            seed=10,
        )
        return response.choices[0].message.content
    except Exception as e:
        print(f"An error occurred: {e}")
        return None

Here is the error message : 
INFO:functions.question_generator:Line 120 <starlette.requests.Request object at 0x7fc180a5bac0>
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
OPIK: Failed to process CreateTraceMessage. Content: CreateTraceMessage(trace_id='067495b3-6170-7490-8000-89b6dd7b7ce6', project_name='Default Project', name='chat_completion_create', start_time=datetime.datetime(2024, 11, 29, 6, 12, 6, 92737, tzinfo=datetime.timezone.utc), end_time=datetime.datetime(2024, 11, 29, 6, 12, 8, 139847, tzinfo=datetime.timezone.utc), input={'messages': [{'role': 'system', 'content': 'You are an experienced interviewer who can read an job description and get all the skills \nrequired by the candidate to be suitable in that job.\n\nJob Description:\n"""\npython engineer\n"""\n\nOutput format:\nSkill 1,Skill 2,Skill 3,.....\n'}]}, output={'choices': [{'finish_reason': 'stop', 'index': 0, 'logprobs': None, 'message': {'content': 'Python programming, Software development, Problem-solving, Version control (Git), Debugging, API development, Data structures and algorithms, Unit testing, Frameworks (e.g., Django, Flask), Database management (SQL, NoSQL), Cloud services (AWS, Azure), Agile methodologies, Collaboration and communication skills.', 'refusal': None, 'role': 'assistant', 'audio': None, 'function_call': None, 'tool_calls': None}}]}, metadata={'model': 'gpt-4o-mini-2024-07-18', 'temperature': 0.5, 'stop': None, 'seed': 10, 'created_from': 'openai', 'type': 'openai_chat', 'id': 'chatcmpl-AYoWXnAhjKpRayg0h4RHbLIcWWGU6', 'created': 1732860729, 'object': 'chat.completion', 'service_tier': None, 'system_fingerprint': 'fp_0705bf87c0', 'usage': {'completion_tokens': 61, 'prompt_tokens': 59, 'total_tokens': 120, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}}, tags=['openai']), Error: RetryError[<Future at 0x7fc16c2bcd60 state=finished raised ConnectError>]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 236, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 256, in handle_request
    raise exc from None
  File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 236, in handle_request
    response = connection.handle_request(
  File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 101, in handle_request
    raise exc
  File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 78, in handle_request
    stream = self._connect(request)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 124, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_backends/sync.py", line 207, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 478, in __call__
    result = fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/opik/rest_api/traces/client.py", line 243, in create_trace
    _response = self._client_wrapper.httpx_client.request(
  File "/usr/local/lib/python3.10/site-packages/opik/rest_api/core/http_client.py", line 213, in request
    response = self.httpx_client.request(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 837, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 926, in send
    response = self._send_handling_auth(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 954, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 991, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1027, in _send_single_request
    response = transport.handle_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 235, in handle_request
    with map_httpcore_exceptions():
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 111] Connection refused

And it is being retried twice.

**Comment by jverre** [comment]
Thanks @Badrinarayana26, we are taking a closer look to make sure the fix we released this morning solves your issues

**Comment by jverre** [comment]
Hi @Badrinarayana26,
Looking at the error above it seems like the issue is with `httpx.ConnectError: [Errno 111] Connection refused`, this indicates that the SDK could not reach the backend server.

To resolve this can you:
1. Run `opik configure` in the terminal: This will guide you through the configuration of the SDK and create a local config file with the right environment variables, it also checks for local running backend
2. Double check that the backend is running by accessing the URL you set in OPIK_URL_OVERRIDE or running:
```
from opik.rest_api import OpikApi

rest_client = OpikApi(base_url="http://localhost:5173/api")

print(rest_client.is_alive())
```

**Comment by jverre** [comment]
@Badrinarayana26 Closing this for now, I think we have resolved the underlying issue

**Comment by Badrinarayana26** [comment]
Working as expected now, thanks for the support!  @jverre
